### PR TITLE
ftp.py -- please check over

### PR DESCRIPTION
**Pull request by DJSanti**
Put in some work on the program. Currently, it can log into jeangourd.com, get the listings, and log back out. This is then written to a .txt file, which is then read out to the command line before the program completes. Now, I know it still needs work, but I'm turning in for tonight. I'll pick it up again tomorrow. Until then, feel free to test/add to it.

### CODE REVIEW

**Review by JohnnySn0w — DISMISSED** [review]

**Comment by DJSanti** [comment]
Didn't mean to dismiss your review.

Anyway, had to implement one more edit. This is my final. I'll see you guys either Sunday or Monday.

Have fun!

**Review by ghost — DISMISSED** [review]
I don’t understand all that is written but based on the little programming knowledge I have this looks good.

**Comment by DJSanti** [comment]
It all works now! I just need it all to go from one or two files instead of my current setup, but its good other than that.

**Review by JohnnySn0w — APPROVED** [review]

**Comment by JohnnySn0w** [comment]
closed in favor of another variation

**Pull request closed without merging**
